# Generated by Django 2.2.5 on 2019-10-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicioprestado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=300)),
                ('Servicio', models.CharField(max_length=300)),
                ('Telefono', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Direccion', models.CharField(max_length=300)),
                ('CodigoPostal', models.CharField(max_length=5)),
                ('Image', models.ImageField(default='media/default.png', upload_to='auto_images')),
            ],
        ),
        migrations.CreateModel(
            name='IdTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAlta', models.DateTimeField(auto_now_add=True)),
                ('Actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiondeTecnicos.Actividades')),
                ('Tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiondeTecnicos.Tecnico')),
            ],
        ),
    ]
