# Generated by Django 2.2.5 on 2019-10-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestiondeTecnicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ApellidoMaterno',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ApellidoPaterno',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='Nombres',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='CodigoPostal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Direccion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Servicio',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='Telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
